### ISSUE TITLE
Question in regards of tx buy-name 

### ISSUE THREAD

**Issue by jaybxyz** [sunnya97/sdk-nameservice-example#6]
It seems like there is no function to request test coins from faucet. 
Is this something that I need to develop ?

**Comment by jaybxyz** [comment]
@sunnya97 I got it by referencing [Joon's project](https://github.com/mossid/sdk-nameservice-example/).

**Comment by sunnya97** [comment]
Hey, this repo has been depreciated.  Please use the one at http://github.com/cosmos/sdk-application-tutorial
